### ISSUE TITLE
visiting /preregistration/confirm with no badge results in error

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1814] opened 2016-04-28 22:38 UTC
don't fix this because it's dumb and no real user is ever going to do it, I just found this

repro steps:
1) visit exactly this URL with no badge_id or params: /uber/preregistration/confirm

expected:  get a redirect back to badge registration page, or an error message
actual: it displays a form with no data in it, and if you click any of the buttons it explodes.

We should detect when there's no 'id' passed in and do something useful instead of weirdly showing a blank form that crashes when you do anything with it.

**Comment by EliAndrewC** [comment] 2017-01-02 19:08
Closing as a duplicate of #2026

**Comment by kitsuta** [comment] 2017-03-14 18:13
Re-opening since #2026 is a pull request, not an issue.

**Comment by BlueHat-GURU** [comment] 2017-03-17 20:59
Still live?

**Comment by kitsuta** [comment] 2017-03-17 23:52
Just tested on the staging server -- confirmed fixed.

**Closed by kitsuta** 2017-03-17 23:52 UTC
Labels: newcomer
