### ISSUE TITLE
[2016]Supporters unable to update their custom badge name or t-shirt size

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1451] opened 2015-09-02 14:59 UTC
After a supporter has purchased their badge, and views their self-service badge management link, the field to modify their badge name and their t-shirt size appear to be missing.

**Comment by kitsuta** [comment] 2015-09-02 15:04
Duplicate of https://github.com/magfest/ubersystem/issues/1430.

**Closed by kitsuta** 2015-09-02 15:04 UTC
