### ISSUE TITLE
Issue reading ''s(quotes) in names

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#1597] opened 2015-11-28 08:41 UTC
https://prime.uber.magfest.org/uber/signups/shifts#/
vs
https://prime.uber.magfest.org/uber/signups/index

Magfest Staffer:  David O'Farrell 

When he signs into this volunteer checklist (the 2nd link) it says:
Volunteer Checklist for David O'Farrell 

When he goes to the sign up for shifts (1st link) it has his name listed as:
`David O&#39;Farrell's available shifts`

Something's not being read correctly there.
Also created: https://jira.magfest.net/browse/MAGDEV-32

**Comment by EliAndrewC** [comment] 2015-11-28 17:14
Sorry, but I've just re-read the names like 5 times and I don't see the difference.  From what you copy/pasted, it looks like it's listing the correct name in both places.

**Comment by earl7399** [comment] 2015-11-28 17:46
Ditto, FWIW.

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086

**Comment by bds002** [comment] 2015-11-28 17:56
On :https://prime.uber.magfest.org/uber/signups/shifts#/
it reads as: David O&#39;Farrell's available shifts

**Comment by earl7399** [comment] 2015-11-28 18:00
I literally have no idea what is wrong with that - it *should* read

*David O'Farrell's available shifts*

...unless I'm completely misunderstanding something.

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086

**Comment by bds002** [comment] 2015-11-28 18:02
https://files.slack.com/files-pri/T02LNLJFA-F0FER3XTL/pasted_image_at_2015_11_28_13_01.png

**Comment by bds002** [comment] 2015-11-28 18:03
That's what I am seeing on that particular page

**Comment by kitsuta** [comment] 2015-11-28 21:45
On today's episode of "HTML codes getting rendered when they shouldn't"...

Btw @bds002 in the future, if there is text that you definitively need to NOT get processed in any way (as is the case here, where the HTML code for apostrophe keeps getting rendered inside comments), surround the offending text with backtick characters (`, above the Tab key).

**Comment by binary1230** [comment] 2015-12-23 19:05
going through this with the intern code team, solution might be something like:

change
```
Hey {{ attendee.date_registered }}, come to MAgfest
```
to
```
Hey {{ attendee.date_registered | safe }}, come to MAgfest
```

(not sure what 'safe' function is called, something like that or safe_html or similar)

**Comment by EliAndrewC** [comment] 2015-12-24 16:25
``safe`` is indeed a thing: https://docs.djangoproject.com/en/1.9/ref/templates/builtins/#safe

**Comment by floraline** [comment] 2017-09-12 16:50
Does this issue still exist? I'm unable to reproduce this on `signups/shifts` with `David O'Farrell`.

**Comment by RobRuana** [comment] 2017-09-12 16:51
@floraline this was _probably_ fixed when we switched to Jinja templates.

**Comment by floraline** [comment] 2017-09-12 17:15
From the [Jinja2 documentation](http://jinja.pocoo.org/docs/2.9/api/): 
```
autoescape

    If set to True the XML/HTML autoescaping feature is enabled by default. 
```

From `uber/jinja.py`:
```
env = jinja2.Environment(
            autoescape=True,
```

Looks like it's fixed.

**Comment by RobRuana** [comment] 2017-09-12 17:57
Fixed by Jinja2!

**Closed by RobRuana** 2017-09-12 17:57 UTC
Labels: low-hanging fruit
