### ISSUE TITLE
Staff member lost badge, swap to attendee had issues assigning #

### ISSUE THREAD

**Issue by earl7399** [magfest/ubersystem#550] opened 2014-09-14 18:25 UTC

**Comment by kitsuta** [comment] 2015-01-19 16:50
So the error you described is "Oh noes, the webserver must be down or something" right?

This happens when the server returns a 500 error while trying to check an attendee in (or performing another Javascript-based action). I expect it was complaining about you trying to check in an attendee that was already checked in, so that's not unexpected.

After testing it in my local server, I can confirm that you can't actually change the badge type, and attempting to do so will remove the badge number.

**Comment by kitsuta** [comment] 2015-01-20 10:52
Whoops, actually we use this for upgrading one-day badges, so it now _really needs_ to be fixed before magfest.

**Comment by EliAndrewC** [comment] 2015-01-21 00:29
I'll take a look at this tonight after I get to the hotel.  I'm in the middle of finishing packing and loading up the car, and I expect that we'll arrive in the next couple of hours (so like definitely before 10pm).  I'll be up for a while since my sleep schedule has been messed up, so I anticipate getting this done tonight at some point.

**Closed** 2015-01-21 07:40 UTC
Labels: before magfest
