### ISSUE TITLE
MAGClassic 2015: Sorting ability on Staffers Screen

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#1265] opened 2015-07-26 11:10 UTC
@thaeli  and team, Would it be possible to make the heading of each column on: 
https://classic.uber.magfest.org/uber/registration/staffers
sortable? - so if I clicked an Badge - it would give me an Alpha sort of all the badges, so I can quickly look at Attendee/Staff badges?

We use the Assigned To: section to sort and quickly see who's not assigned anywhere. 

The Hours section to sort through who has hours listed and who hasn't signed up for hours.
  
These where options I had at M13 and we end up use a LOT to manage staff across the board.  
https://prime.uber.magfest.org/m13/registration/staffers?order=weighted_hours

**Comment by binary1230** [comment] 2015-07-26 16:33
going to poke at this, looks like the sorting stuff all still works we just need to add the hyperlinks back in.

**Comment by kitsuta** [comment] 2015-07-26 16:38
Duplicate of https://github.com/magfest/ubersystem/issues/1159

I don't think server-side sorting is a good solution, it's very slow compared to client-side. However, I still don't know why (or even _how_) @EliAndrewC disabled the client-side sorting we had in the Anthrocon branch.

**Comment by binary1230** [comment] 2015-07-26 16:52
gotcha. yea my fix just re-enables whatever it was doing before the refactor

**Comment by EliAndrewC** [comment] 2015-07-26 21:15
> However, I still don't know why (or even how) @EliAndrewC disabled the client-side sorting we had in the Anthrocon branch.

No idea myself, I didn't mean to disable it and hadn't noticed that it wasn't working anymore :(

**Closed** 2015-07-27 13:36 UTC
