### ISSUE TITLE
Add t-shirt sizing guide

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1219] opened 2015-07-14 21:56 UTC
Next to t-shirt size put: "Size guides: Unisex (http://www.mygildan.com/Categories/T-Shirts/Short-Sleeve//p/2000L), Female (http://www.mygildan.com/Categories/T-Shirts/Short-Sleeve//p/2000L)"

**Comment by kitsuta** [comment] 2015-07-15 21:15
These both link to the same thing.

**Comment by nickthenewbie1** [comment] 2015-07-15 23:09
Sorry here's the unisex one: http://www.mygildan.com/Categories/T-Shirts/Short-Sleeve//p/2000

**Comment by EliAndrewC** [comment] 2015-07-19 19:32
Since this has been fixed and I've confirmed the fix on my machine, I'm marking this as closed.

**Closed by EliAndrewC** 2015-07-19 19:32 UTC
Labels: fixed
