### ISSUE TITLE
Unexpected badge behavior / classification.

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#1572] opened 2015-10-31 20:46 UTC
For MAGFest 2016 - Department heads are evaluating their staffers and figuring out who is or is not coming to the event.  There is a report that shows all staff place holders badges:
https://prime.uber.magfest.org/uber/registration/placeholders?department=

If a badge is set to either Invalid (Invalid for the event), or Deferred (does this mean deferred to the next event).  The staffer in question is still showing up on the placeholder report.  This has the affect of making the department heads believe that staffer/attendee might still be coming to the event.

A badge that is set to Invalid or deferred, should not be showing up in day-to-day production level reports/list.  I have reports from both Tech-Ops and Arcade departments as well as Staff Operations about this badge behavior.

**Comment by EliAndrewC** [comment] 2016-02-20 00:05
Closing as a duplicate of #1625

**Closed by EliAndrewC** 2016-02-20 00:05 UTC
