### ISSUE TITLE
Group reg button does not create group reg

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1193] opened 2015-07-05 19:02 UTC
It appears to change some of the field names on the pre-reg form, but the item added to your cart appears to be a standard attendee registration.

**Comment by EliAndrewC** [comment] 2015-07-09 02:22
I'm closing this as a duplicate of #1166 since I fixed that in the pull request linked in that ticket.

**Closed by EliAndrewC** 2015-07-09 02:22 UTC
