### ISSUE TITLE
GET TO DA BADGE NUMBA!

### ISSUE THREAD

**Issue by RobRuana** [magfest/ubersystem#2703] opened 2017-07-20 02:13 UTC
![get-to-da-badge-numba](https://user-images.githubusercontent.com/2592431/28397423-695e83d0-6ccf-11e7-9ac7-19d7ea327728.png)

```
   The above exception was the direct cause of the following exception:
   
   Traceback (most recent call last):
     File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
       response.body = self.handler()
     File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 220, in __call__
       self.body = self.oldhandler(*args, **kwargs)
     File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
       return self.callable(*self.args, **self.kwargs)
     File "/usr/local/uber/plugins/uber/uber/decorators.py", line 242, in with_timing
       return func(*args, **kwargs)
     File "/usr/local/uber/plugins/uber/uber/decorators.py", line 233, in with_caching
       return func(*args, **kwargs)
     File "/usr/local/uber/plugins/uber/uber/decorators.py", line 261, in with_session
       session.commit()
     File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 874, in commit
       self.transaction.commit()
     File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 465, in commit
       t[1].commit()
     File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1632, in commit
       self._do_commit()
     File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1663, in _do_commit
       self.connection._commit_impl()
     File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 723, in _commit_impl
       self._handle_dbapi_exception(e, None, None, None, None)
     File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
       exc_info
     File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
       reraise(type(exception), exception, tb=exc_tb, cause=cause)
     File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
       raise value.with_traceback(tb)
     File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 721, in _commit_impl
       self.engine.dialect.do_commit(self.connection)
     File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 443, in do_commit
       dbapi_connection.commit()
   sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) duplicate key value violates unique constraint "attendee_badge_num_key"
   DETAIL:  Key (badge_num)=(119) already exists.
```

Relevant URL:
```
Request: POST /uber/preregistration/register_group_member HTTP/1.0
```

**Comment by kitsuta** [comment] 2017-07-20 04:08
Having looked at the full stacktrace, this was triggered by someone registering as a group member... a process which deletes the badge they are claiming. This is highly likely to be a dupe of this bug: https://github.com/magfest/ubersystem/issues/2675

**Closed** 2017-07-23 17:05 UTC
Labels: code health, priority:critical
