### ISSUE TITLE
On the Pending E-mails page, refunded examples fails

### ISSUE THREAD

**Issue by earl7399** [magfest/ubersystem#2183] opened 2016-12-05 14:53 UTC
Clicking the examples for MAGFest payment refunded produces an error that ends with:

    raise TemplateDoesNotExist(', '.join(not_found))
django.template.base.TemplateDoesNotExist: emails/reg_workflow/payment_refunded.txt

**Comment by binary1230** [comment] 2016-12-05 15:14
yea weirdly that payment_refunded.txt file actually doesn't exist, dupe of https://github.com/magfest/ubersystem/issues/2116

**Closed** 2016-12-08 05:00 UTC
