### ISSUE TITLE
MAGClassic (and all others): Need way to send confirmation emails to cash paid attendees

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1254] opened 2015-07-23 18:42 UTC
If someone buys a pass from me in cash while i'm out doing promo (ie not at-con mode), I add them manually as an attendee, and manually mark that they pay as cash. They receive no confirmation email and there's no easily searchable way to see that they paid cash.

Is there any way to make it so that I can record a cash sale that sends them a confirmation email, and I can easily look up who paid cash?

**Comment by EliAndrewC** [comment] 2015-07-23 18:44
It should send them a confirmation email if they're marked as paid.  If it's not doing that, then it's a bug.

**Comment by nickthenewbie1** [comment] 2015-07-23 18:48
The marked as paid field is now missing. Huh. Well that's a bug.

**Comment by kitsuta** [comment] 2015-07-24 15:50
@nickthenewbie1, can you create an admin account for me on production so I can look into this? The payment field should never go missing.

**Comment by kitsuta** [comment] 2015-07-24 17:13
Ahhh, oops. That's this line in the plugin: `$.field('amount_extra').parents('.form-group').hide()` - let me add another issue and then fix it.

**Comment by kitsuta** [comment] 2015-07-25 13:38
Now that the payment field is actually enabled, this works for me - I can add an attendee and they'll get sent a payment confirmation email a few minutes later. @nickthenewbie1 can you confirm?

**Comment by nickthenewbie1** [comment] 2015-07-27 19:19
I tried for this attendee, and I do not see an email to them in the log: https://classic.uber.magfest.org/uber/registration/form?id=175c03c5-2786-4a63-a721-de75b9644454

**Comment by kitsuta** [comment] 2015-07-31 17:36
I believe we've fixed the email errors - it looks like the system was choking on an error for sending group emails and that was affecting other emails. @nickthenewbie1 can you let me know the next time you create an attendee?

**Comment by kitsuta** [comment] 2015-07-31 21:03
This was caused by https://github.com/magfest/ubersystem/issues/1294 and https://github.com/magfest/ubersystem/issues/1326, which are both fixed now, so I'm closing this.

**Closed by kitsuta** 2015-07-31 21:03 UTC
