### ISSUE TITLE
Change ribbon dropdown to checklist

### ISSUE THREAD

**Issue by BlueHat-GURU** [magfest/ubersystem#2494] opened 2017-05-22 02:51 UTC
Currently only one ribbon type allowed per person

https://docs.google.com/document/d/1UhcLdu6ShDq3mCRp0LwvKF15y0jw0CGTJQWhnXTwlec/edit?pli=1#heading=h.1we7756nij2t

**Comment by thaeli** [comment] 2017-05-22 04:31
duplicate of #1664

**Closed by thaeli** 2017-05-22 04:31 UTC
