### ISSUE TITLE
Create transactional automated email for refunds.

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#1646] opened 2016-01-22 18:25 UTC
Staffers have come to us in at past events forbbadge refunds when their hours are marked as completed. 

With the new volunteers due refunds page, we are capable of processing refunds without the volunteer being present.  We should create an email that is sent to them when we mark their badge as being refunded....

**Comment by kitsuta** [comment] 2016-01-22 20:16
Duplicate of https://github.com/magfest/ubersystem/issues/1645.

**Closed by kitsuta** 2016-01-22 20:16 UTC
