### ISSUE TITLE
As a staffer I would like my badge number to not change after the staff badge deadline.

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#2171] opened 2016-11-28 22:13 UTC
For MAGfest 2017, we have sent the Staff badge export (Name and numbers) to the printer already.

We have a number of staffers that hadn't completed their Staff checklist (or confirmed their badge yet).
This includes a number of departmentally assigned placeholder badges.  When a Staffer now goes to complete their Staff Checklist/Badge confirmation Uber is changing their badge to an Attendee badge.

If the Staffer had a badge # before the deadline, we want that number to stay, unless an Admin changes the badge to an attendee badge. Since we have already started printing badges, we don't want Uber to make database changes to the numbers based on a deadline.

Reference badge number 799 (Parsley).  Their badge should still be a viable Staff badge as it's being made at the printers as such. @earl7399 discovered this in a response from the staffer.

**Comment by kitsuta** [comment] 2016-11-30 00:33
I have moved this to 'pending design' because I was not able to reproduce this on staging. We have a workaround for giving people their staff badges back, though. I think.

**Comment by kitsuta** [comment] 2016-12-08 05:13
Closing as duplicate of #2179.

**Closed by kitsuta** 2016-12-08 05:13 UTC
