### ISSUE TITLE
MAGStock 7: Attendee Name is Fucked on Shift Signup Page

### ISSUE THREAD

**Issue by Hachi05** [magfest/ubersystem#2505] opened 2017-05-28 07:55 UTC
![image](https://cloud.githubusercontent.com/assets/7577129/26527047/7ca6a138-4359-11e7-8fd5-ce97900cf9bf.png)

**Comment by kitsuta** [comment] 2017-05-28 13:59
Dupe of https://github.com/magfest/ubersystem/issues/2466.

**Closed by kitsuta** 2017-05-28 13:59 UTC
