### ISSUE TITLE
Volunteers Owed refunds.... - Hours are marked, still on sheet

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#1800] opened 2016-03-04 21:07 UTC
For the third section of this report:
https://prime.uber.magfest.org/uber/summary/volunteers_owed_refunds

There is a staffers that was schedule for 31 hours - so he would have been refund eligible.
He is marked as being in the section as possible eligible for refund if hours are marked.

All hours are marked - however most of them are marked as "Staffer didn't show up"
That should count as a marked shift, just simply ineligible.

Staff in question: Luc Hale.

**Comment by EliAndrewC** [comment] 2016-03-08 21:20
Closing as a duplicate of #1803 which I thought hadn't already been filed.  MY BAD.

**Closed by EliAndrewC** 2016-03-08 21:20 UTC
