### ISSUE TITLE
Active bug preventing group pre-reg with >1 member

### ISSUE THREAD

**Issue by earl7399** [magfest/ubersystem#2071] opened 2016-09-24 19:39 UTC
Bug is tested and present in staging
Fill out group pre-registration info, click Add to Cart, cart has group with single badge in it. Attempts to update the # of badges leave a single badge in the group.

**Comment by earl7399** [comment] 2016-09-24 19:45
Update - creating the group with 13 badges in the admin interface results in a 1-badge group as well

**Comment by binary1230** [comment] 2016-09-24 20:25
almost positive this is the same thing as this: https://github.com/magfest/ubersystem/issues/2068

**Comment by binary1230** [comment] 2016-09-24 20:28
ok if you debug the unit test the part that is failing is this block of code in ```assign_badges()``` is failing:

```
            elif diff > 0 and group.cost != 0:
                group.cost += diff * group.new_badge_cost
                for i in range(diff):
                    group.attendees.append(Attendee(badge_type=new_badge_type, ribbon=ribbon_to_use, paid=paid, **extra_create_args))
```

diff is 2 (the amount of badges requested), but group.cost IS zero, so it doesn't add the badges.  thus group.badges is zero.

I think somewhere eli left some comments somewhere about how to fix this.

**Comment by kitsuta** [comment] 2016-09-24 21:14
Eli's comment's are wrong, as I've said about the FIFTH time now. We don't check if auto_recalc is on on _purpose_, because we've turned it off for everyone, because it's _seriously broken_ with bucket-based pricing.

But yeah, this is clearly a bad change, shoot. We need to revert this on an emergency basis.

**Comment by kitsuta** [comment] 2016-09-25 10:03
This is confirmed fixed with https://github.com/magfest/ubersystem/pull/2072.

**Closed by kitsuta** 2016-09-25 10:03 UTC
