### ISSUE TITLE
development.ini not overriding default settings with [[enums]] section

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#803] opened 2014-12-02 18:02 UTC
It might have been a caffeine induced hallucination at 3am so I'm not actually sure this is what was happening, but, bugging it before I forget:

development.ini is not overriding some config values correctly.

to repro:
1) Put an ```[[enum]]``` section in both development-defaults.ini and development.ini with different values.

EXPECTED: development.ini [[enum]] value is used and development-defaults.ini is ignored.
ACTUAL: development-defaults.ini [[enum]] value is used and development.ini is ignored.

The workaround is easy (remove the sections from development-defauts.ini and put them in puppet).  but we probably should fix what's going on with this config at some point.

-Dom

**Comment by kitsuta** [comment] 2015-01-10 04:52
I cannot reproduce this. I tried changing the name of a ribbon using development.ini and it worked fine.

**Comment by EliAndrewC** [comment] 2015-01-10 04:55
Good enough for me.  Closing as "Dom was sleep deprived".

**Closed by EliAndrewC** 2015-01-10 04:55 UTC
Labels: soon
