### ISSUE TITLE
Hotel rooms link 

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#1476] opened 2015-09-07 19:17 UTC
With the new Puppetization of the Staff rooms work flow, we need to add the links back into the Site map:

https://magstock.uber.magfest.org/uber/accounts/sitemap

I thought I had already submitted this as a request... but maybe not.

**Comment by binary1230** [comment] 2015-10-01 23:21
closing as a duplicate of https://github.com/magfest/ubersystem/issues/1428

@bds002 if that's not a duplicate, please re-open

**Closed by binary1230** 2015-10-01 23:21 UTC
